// Generated from current production ITelRilManager; no test implementation copied.
// Interface SHA256: aecd4286633b981cf6334e9866a5f8c901eb4d77f00058df785d5cb0d4d1bbb0
#pragma once
#include <gmock/gmock.h>
#include "i_tel_ril_manager.h"
#include "telephony_errors.h"
namespace OHOS::Telephony {
class MockTelRilManager : public ITelRilManager {
public:
    MOCK_METHOD(bool, OnInit, (), (override));
    MOCK_METHOD(bool, DeInit, (), (override));
    MOCK_METHOD(int32_t, RegisterCoreNotify, (int32_t, const std::shared_ptr<AppExecFwk::EventHandler> &, int32_t, int32_t *), (override));
    MOCK_METHOD(int32_t, UnRegisterCoreNotify, (int32_t, const std::shared_ptr<AppExecFwk::EventHandler> &, int32_t), (override));
    MOCK_METHOD(int32_t, InitTelExtraModule, (int32_t), (override));
    MOCK_METHOD(int32_t, SetRadioState, (int32_t, int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetRadioState, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, ShutDown, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetCallList, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, Dial, (int32_t, std::string, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, Reject, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, Hangup, (int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, Answer, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, HoldCall, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, UnHoldCall, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SwitchCall, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, CombineConference, (int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SeparateConference, (int32_t, int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, CallSupplement, (int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetCallWaiting, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetCallWaiting, (int32_t, const int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetCallTransferInfo, (int32_t, const int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetCallTransferInfo, (int32_t, const CallTransferParam &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetClip, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetClip, (int32_t, const int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetClir, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetClir, (int32_t, const int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetCallRestriction, (int32_t, std::string, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetCallRestriction, (int32_t, const CallRestrictionParam &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetBarringPassword, (int32_t, const char *, const char *, const std::string &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendDtmf, (int32_t, const DtmfParam &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendDtmf, (int32_t, char, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, StartDtmf, (int32_t, char, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, StopDtmf, (int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetVoNRSwitch, (int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetSignalStrength, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetCsRegStatus, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetPsRegStatus, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetOperatorInfo, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetNeighboringCellInfoList, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetCurrentCellInfo, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetImei, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetImeiSv, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetMeid, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetVoiceRadioTechnology, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetPhysicalChannelConfig, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetBasebandVersion, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetLocateUpdates, (int32_t, RegNotifyMode, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendGsmSms, (int32_t, std::string, std::string, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendCdmaSms, (int32_t, std::string, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, AddSimMessage, (int32_t, const SimMessageParam &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, DelSimMessage, (int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, UpdateSimMessage, (int32_t, const SimMessageParam &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetSmscAddr, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetCdmaCBConfig, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetSmscAddr, (int32_t, int32_t, std::string, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetCBConfig, (int32_t, const CBConfigParam &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetCdmaCBConfig, (int32_t, CdmaCBConfigInfoList &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetCBConfig, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendSmsMoreMode, (int32_t, std::string, std::string, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendSmsAck, (int32_t, bool, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, AddCdmaSimMessage, (int32_t, int32_t, std::string, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, DelCdmaSimMessage, (int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, UpdateCdmaSimMessage, (int32_t, const CdmaSimMessageParam &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetInitApnInfo, (int32_t, const DataProfile &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, ActivatePdpContext, (int32_t, const ActivateDataParam &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, DeactivatePdpContext, (int32_t, int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetPdpContextList, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetLinkBandwidthInfo, (int32_t, const int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetLinkBandwidthReportingRule, (int32_t, LinkBandwidthRule, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetDataPermitted, (int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetLinkCapability, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, CleanAllConnections, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendUrspDecodeResult, (int32_t, std::vector<uint8_t>, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendUePolicySectionIdentifier, (int32_t, std::vector<uint8_t>, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendImsRsdList, (int32_t, std::vector<uint8_t>, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetNetworkSliceAllowedNssai, (int32_t, std::vector<uint8_t>, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetNetworkSliceEhplmn, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetSimStatus, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetSimIO, (int32_t, SimIoRequestInfo, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetImsi, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetSimLockStatus, (int32_t, std::string, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetSimLock, (int32_t, const SimLockParam &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, ChangeSimPassword, (int32_t, const SimPasswordParam &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, UnlockPin, (int32_t, const std::string &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, UnlockPuk, (int32_t, const std::string &, const std::string &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, UnlockPin2, (int32_t, const std::string &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, UnlockPuk2, (int32_t, const std::string &, const std::string &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetActiveSim, (int32_t, int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendTerminalResponseCmd, (int32_t, const std::string &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendEnvelopeCmd, (int32_t, const std::string &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendCallSetupRequestResult, (int32_t, bool, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SimStkIsReady, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, UnlockSimLock, (int32_t, int32_t, std::string, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetRadioProtocol, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetRadioProtocol, (int32_t, RadioProtocol, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetNetworkSearchInformation, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetNetworkSelectionMode, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetNetworkSelectionMode, (int32_t, int32_t, std::string, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetPreferredNetwork, (int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetPreferredNetwork, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetCallPreferenceMode, (int32_t, const int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetCallPreferenceMode, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetUssd, (int32_t, const std::string, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetUssd, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, CloseUnFinishedUssd, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetMute, (int32_t, const int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetMute, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetEmergencyCallList, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetEmergencyCallList, (int32_t, const std::vector<EmergencyCall> &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetCallFailReason, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SimOpenLogicalChannel, (int32_t, const std::string &, const int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SimOpenLogicalChannelWithPort, (int32_t, const std::string &, const int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SimCloseLogicalChannel, (int32_t, const int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SimTransmitApduLogicalChannel, (int32_t, const ApduSimIORequestInfo &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SimTransmitApduBasicChannel, (int32_t, const ApduSimIORequestInfo &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SimAuthentication, (int32_t, const SimAuthenticationRequestInfo &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SendSimMatchedOperatorInfo, (int32_t, const NcfgOperatorInfo &, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetNotificationFilter, (int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetDeviceState, (int32_t, int32_t, bool, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetNrOptionMode, (int32_t, int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetNrOptionMode, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetRrcConnectionState, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetNrSsbId, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, GetPrimarySlot, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MOCK_METHOD(int32_t, SetPrimarySlot, (int32_t, const AppExecFwk::InnerEvent::Pointer &), (override));
    MockTelRilManager()
    {
        ON_CALL(*this, OnInit()).WillByDefault(testing::Return(false));
        ON_CALL(*this, DeInit()).WillByDefault(testing::Return(false));
        ON_CALL(*this, RegisterCoreNotify(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, UnRegisterCoreNotify(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, InitTelExtraModule(testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetRadioState(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetRadioState(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, ShutDown(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetCallList(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, Dial(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, Reject(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, Hangup(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, Answer(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, HoldCall(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, UnHoldCall(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SwitchCall(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, CombineConference(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SeparateConference(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, CallSupplement(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetCallWaiting(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetCallWaiting(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetCallTransferInfo(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetCallTransferInfo(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetClip(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetClip(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetClir(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetClir(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetCallRestriction(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetCallRestriction(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetBarringPassword(testing::_, testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendDtmf(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendDtmf(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, StartDtmf(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, StopDtmf(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetVoNRSwitch(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetSignalStrength(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetCsRegStatus(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetPsRegStatus(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetOperatorInfo(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetNeighboringCellInfoList(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetCurrentCellInfo(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetImei(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetImeiSv(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetMeid(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetVoiceRadioTechnology(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetPhysicalChannelConfig(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetBasebandVersion(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetLocateUpdates(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendGsmSms(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendCdmaSms(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, AddSimMessage(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, DelSimMessage(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, UpdateSimMessage(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetSmscAddr(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetCdmaCBConfig(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetSmscAddr(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetCBConfig(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetCdmaCBConfig(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetCBConfig(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendSmsMoreMode(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendSmsAck(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, AddCdmaSimMessage(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, DelCdmaSimMessage(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, UpdateCdmaSimMessage(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetInitApnInfo(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, ActivatePdpContext(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, DeactivatePdpContext(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetPdpContextList(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetLinkBandwidthInfo(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetLinkBandwidthReportingRule(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetDataPermitted(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetLinkCapability(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, CleanAllConnections(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendUrspDecodeResult(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendUePolicySectionIdentifier(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendImsRsdList(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetNetworkSliceAllowedNssai(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetNetworkSliceEhplmn(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetSimStatus(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetSimIO(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetImsi(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetSimLockStatus(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetSimLock(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, ChangeSimPassword(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, UnlockPin(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, UnlockPuk(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, UnlockPin2(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, UnlockPuk2(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetActiveSim(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendTerminalResponseCmd(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendEnvelopeCmd(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendCallSetupRequestResult(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SimStkIsReady(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, UnlockSimLock(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetRadioProtocol(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetRadioProtocol(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetNetworkSearchInformation(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetNetworkSelectionMode(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetNetworkSelectionMode(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetPreferredNetwork(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetPreferredNetwork(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetCallPreferenceMode(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetCallPreferenceMode(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetUssd(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetUssd(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, CloseUnFinishedUssd(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetMute(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetMute(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetEmergencyCallList(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetEmergencyCallList(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetCallFailReason(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SimOpenLogicalChannel(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SimOpenLogicalChannelWithPort(testing::_, testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SimCloseLogicalChannel(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SimTransmitApduLogicalChannel(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SimTransmitApduBasicChannel(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SimAuthentication(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SendSimMatchedOperatorInfo(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetNotificationFilter(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetDeviceState(testing::_, testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetNrOptionMode(testing::_, testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetNrOptionMode(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetRrcConnectionState(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetNrSsbId(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, GetPrimarySlot(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
        ON_CALL(*this, SetPrimarySlot(testing::_, testing::_)).WillByDefault(testing::Return(TELEPHONY_ERR_RIL_CMD_FAIL));
    }
};
}
